#!/usr/bin/env bash
ERR=0
while read -r ORIG
do
    if [[ ! -e "rendered/$ORIG" ]]
    then
        echo "Can't find '$ORIG'" >> /dev/stderr
        ERR=1
    fi
done < <(cd _site && find .)
exit "$ERR"
