#!/usr/bin/env bash
RESULT=$(linkchecker --no-status                   \
                     --ignore-url=.xml             \
                     --ignore-url=/git             \
                     --ignore-url=/projects/repos  \
                     --config=static/linkcheckerrc \
                     rendered/index.html 2>&1)
CODE="$?"

[[ "$CODE" -eq 0 ]] || echo "$RESULT"

exit "$CODE"
