#!/usr/bin/env bash

function mkConfig {
  echo '[filtering]'
  echo "localwebroot=file://$rendered/"
  echo 'ignorewarnings=file-missing-slash'
}

export HOME="$PWD/home"
mkdir -p "$HOME/.linkchecker"

mkConfig > "$HOME/.linkchecker/linkcheckerrc"

RESULT=$(linkchecker --no-status                  \
                     --ignore-url=.xml            \
                     --ignore-url=/git            \
                     --ignore-url=/projects/repos \
                     "$rendered/index.html" 2>&1)
CODE="$?"

[[ "$CODE" -eq 0 ]] || echo "$RESULT"

exit "$CODE"
