#!/usr/bin/env bash

# Indenting HTML is nice, but if we do it on pre/code blocks then the whitespace
# appears verbatim in the page.

F="$rendered/blog/2017-01-14-rss_to_maildir.html"

[[ -f "$F" ]] || {
    echo "Example file '$F' not found in '$PWD'" 1>&2
    exit 1
}

if grep ' [ ]*<pre' < "$F"
then
    echo "Source code is indented; this will be visible on the page" 1>&2
    exit 1
fi

exit 0
