#!/usr/bin/env bash
set -e

# Indenting HTML is nice, but if we do it on pre/code blocks then the whitespace
# appears verbatim in the page.

grep ' [ ]*<pre' < "$1" &&
    fail "Source code is indented; this will be visible on the page"

exit 0
