#!/usr/bin/env bash

function fail {
    echo "FAIL: $1" 1>&2
    exit 1
}

echo '<pre><code></code></pre>' | cleanup > out.html

grep -q '<code>' < out.html && fail "Didn't strip <code>"
grep -q '<pre>'  < out.html && fail "Didn't strip <pre>"

echo "Success" 1>&2
