#!/usr/bin/env bash

function fail {
    echo "FAIL: $1" 1>&2
    exit 1
}

echo '<pre><code></code></pre>' > source
SOURCE="$PWD/source" DEST="$PWD/dest" render_page

grep '<code>' < dest > /dev/null && fail "Didn't strip <code>"
grep '<pre>' < dest > /dev/null && fail "Didn't strip <pre>"

echo "Success" 1>&2
