#!/usr/bin/env bash

function fail {
    echo "FAIL: $1" >> /dev/stderr
    exit 1
}

OUTPUT=$(echo '<pre><code></code></pre>' | ./static/render_page)

echo "$OUTPUT" | grep '<code>' > /dev/null && fail "Didn't strip <code>"
echo "$OUTPUT" | grep '<pre>'  > /dev/null && fail "Didn't strip <pre>"

echo "Success" >> /dev/stderr
