#!/usr/bin/env bash
set -e

ERR=0

while read -r PRJ_FILE_OR_LINK
do
    PRJ_FILE=$(readlink "$PRJ_FILE_OR_LINK")
    [[ -f "$PRJ_FILE" ]] || continue  # Skip directories
    ESSAY_FILE=$(echo "$PRJ_FILE" | sed -e 's@/projects/@/essays/@g')
    [[ -e "$ESSAY_FILE" ]] || {
        ERR=1
        echo "Couldn't find expected redirect '$ESSAY_FILE'" 1>&2
        continue
    }

    PRJ_URL=$(relTo "$PRJ_FILE" $(dirname "$ESSAY_FILE") |
                  sed -e 's@^./@@g')

    FOUND=0
    while read -r URL
    do
        if [[ "x$URL" = "x$PRJ_URL" ]]
        then
            FOUND=1
        fi
    done < <(grep -o '<link rel="canonical" href="[^"]*' < "$ESSAY_FILE" |
             grep -o 'href=".*' | grep -o '".*' | tr -d '"' | sed -e 's@^./@@g')

    if [[ "$FOUND" -eq 0 ]]
    then
        ERR=1
        echo "'$ESSAY_FILE' doesn't redirect to '$PRJ_URL'" 1>&2
        grep '<link rel="canonical"' < "$ESSAY_FILE"
    fi
done < <(find -L "$rendered/projects" -type f -o -type l)

exit "$ERR"
