#!/usr/bin/env bash

ERR=0

while read -r PRJ_FILE
do
    ESSAY_FILE=$(echo "$PRJ_FILE" | sed -e 's@/projects/@/essays/@g')
    [[ -e "$ESSAY_FILE" ]] || {
        ERR=1
        echo "Couldn't find expected redirect '$ESSAY_FILE'" 1>&2
        continue
    }

    PRJ_URL=$(relTo "$PWD/rendered" "$PRJ_FILE")
    grep "<link rel=\"canonical\" href=\"$PRJ_URL\"/>" < "$ESSAY_FILE" \
                                                       > /dev/null || {
        ERR=1
        echo "'$ESSAY_FILE' doesn't redirect to '$PRJ_URL'" 1>&2
        grep '<link rel="canonical"' < "$ESSAY_FILE"
    }
done < <(find "$PWD/rendered/projects" -type f)

exit "$ERR"
