#!/usr/bin/env bash

ERR=0
# shellcheck disable=SC2154
for FILE in "$rendered"/*.html
do
    DIR=$(basename "$FILE" .html)
    if [[ -d "$DIR" ]]
    then
        while read -r ENTRY
        do
            if ! echo "$ENTRY" | grep "[^/][^/]*\.[^/][^/]*" > /dev/null
            then
                echo "File '$ENTRY' has no extension" 1>&2
                ERR=1
            fi
        done < <(find "$DIR" -type f -o -type -l)
    fi
done

exit "$ERR"
