#!/usr/bin/env bash

ERR=0
for REPO in ~/Programming/repos/*.git
do
    NAME=$(basename "$REPO" .git)
    if [[ ! -e "rendered/projects/repos/$NAME.html" ]]
    then
        ERR=1
        echo "No repo page for $NAME" 1>&2
    fi
done

exit "$ERR"
