#!/usr/bin/env bash

ERR=0
while read -r SOURCE
do
    NAME=$(echo "$SOURCE" | rev | cut -d '.' -f 2- | rev)
    DEST="/projects/$NAME.html"
    if [[ ! -e "rendered$DEST" ]]
    then
        echo "Can't find rendered$DEST" >> /dev/stderr
        ERR=1
    fi
    LINK=$(xidel - -q --extract "//a[@href='$DEST']/@href" < rendered/projects.html)
    if ! echo "$LINK" | grep "$NAME" > /dev/null
    then
        echo "blog/$NAME.html doesn't appear in blog.html" >> /dev/stderr
        ERR=1
    fi
done < <(find projects -type f -name "index.*")

exit "$ERR"
