#!/usr/bin/env bash
shopt -s nullglob

REPO_DIR="/home/chris/Programming/repos"

[[ -e "$REPO_DIR" ]] || {
    echo "Couldn't find repo dir '$REPO_DIR', skipping test" 1>&2
    exit 0
}

ERR=0
for REPO in "$REPO_DIR"/*.git
do
    NAME=$(basename "$REPO" .git)
    if [[ ! -e "$rendered/projects/repos/$NAME.html" ]]
    then
        ERR=1
        echo "No repo page for $NAME" 1>&2
    fi
done

if [[ "$ERR" -gt 0 ]]
then
    echo "Found repos:"             1>&2
    find "$rendered/projects/repos" 1>&2
fi

exit "$ERR"
