#!/usr/bin/env bash

function indices {
    # shellcheck disable=SC2154
    find "$rendered/projects" -name "index.*"
}

ERR=0
while read -r NAME
do
    [[ "x$NAME" = "x$rendered/projects/index.html" ]] && continue

    NOREND=$(echo "$NAME" | sed -e 's@^/nix/store/[^/]*/@@g')
    DEST="./$NOREND"
    if [[ ! -e "$rendered/$DEST" ]]
    then
        echo "Can't find $rendered/$DEST" 1>&2
        ERR=1
    fi
    LINK=$(xidel - -q --extract \
                 "//a[@href='$DEST']/@href" < "$rendered/projects.html")
    if ! echo "$LINK" | grep "$DEST" > /dev/null
    then
        echo "$NAME ($DEST) doesn't appear in projects.html" 1>&2
        ERR=1
    fi
done < <(indices)

exit "$ERR"
