#!/usr/bin/env bash

function fail() {
  echo "FAIL: $*" 1>&2
  exit 1
}

[[ -e rendered/blog.atom ]] || fail "No blog.atom"
[[ -e rendered/blog.rss  ]] || fail "No blog.rss"

for FEED in blog.atom blog.rss
do
  for PAGE in index.html blog.html
  do
    grep "$FEED" < "rendered/$PAGE" || fail "$FEED isn't in $PAGE"
  done
done
