#!/usr/bin/env python3

import mf2py
import os
import subprocess
import sys

def render_hcard():
    out = subprocess.check_output(["renderHcard"], shell=True)
    parser = mf2py.Parser(doc=out, html_parser='html5lib')
    items  = parser.to_dict(filter_by_type='h-card')
    if len(items) != 1:
        fail('Generated ' + str(len(items)) + ' h-cards')
    return items[0]

def fail(m):
    print('FAIL: ' + m)
    sys.exit(1)

def run_checks_on(to_check, checks):
    list(map(lambda b_m: b_m[0] or fail(b_m[1] + ': ' + repr(to_check)), checks))

def check_hcard(card):
    run_checks_on(card, [
        (card['type'] == ['h-card'],
         'Not a h-card'),

        (len(card['properties']['url']) == 1,
         "Card doesn't have 1 URL"),

        (card['properties']['url'][0].endswith('chriswarbo.net'),
         "Card isn't chriswarbo.net"),

        (len(card['properties']['name']) == 1,
         "Card doesn't have 1 name"),

        (card['properties']['name'][0] == 'Chris Warburton',
         "Card isn't Chris Warburton")
    ])

check_hcard(render_hcard())
