#!/usr/bin/env bash

# use relative links, rather than absolute links to chriswarbo.net

function get_urls() {
    P1="not(contains(@class, 'author'))"
    P2="not(contains(@rel,   'author'))"
    P3="not(contains(@rel,   'me'))"
    PRED="[$P1 and $P2 and $P3]"
    xidel - -s --extract "//*$PRED/@href" < "$1"
    xidel - -s --extract "//*$PRED/@src"  < "$1"
}

ERR=0
FILE="$1"
if echo "$FILE" | grep "README" > /dev/null
then
    # Skip repos, since their READMEs might contain anything
    exit 0
fi

# Strip out anything after a '/', since we only care about the domain name.
# To make this work, we also have to strip out the protocol (e.g. http://)
# since that obviously contains a '/'.
if get_urls "$FILE" | sed -e 's@^.*://@@g' -e 's@/.*$@@g' |
                      grep "chriswarbo\\.net"
then
    echo "Found absolute links to chriswarbo.net in '$FILE'" 1>&2
    ERR=1
fi
if get_urls "$FILE" | grep "^/"
then
    echo "Found link to root (/) in '$FILE'" 1>&2
    ERR=1
fi

exit "$ERR"
