#!/usr/bin/env bash

# use relative links, rather than absolute links to chriswarbo.net

function get_urls() {
    P1="not(contains(@class, 'author'))"
    P2="not(contains(@rel,   'author'))"
    P3="not(contains(@rel,   'me'))"
    PRED="[$P1 and $P2 and $P3]"
    xidel - -q --extract "//*$PRED/@href" < "$1"
    xidel - -q --extract "//*$PRED/@src"  < "$1"
}

ERR=0
while read -r FILE
do
    if echo "$FILE" | grep "projects/repos/" > /dev/null
    then
        # Skip repos, since their READMEs might contain anything
        continue
    fi
    if get_urls "$FILE" | grep "chriswarbo\.net"
    then
        echo "Found absolute links to chriswarbo.net in '$FILE'" 1>&2
        ERR=1
    fi
    if get_urls "$FILE" | grep "^/"
    then
        echo "Found link to root (/) in '$FILE'" 1>&2
        ERR=1
    fi
done < <(find rendered -name "*.html")

exit "$ERR"
