#!/usr/bin/env bash

function get_imgs() {
    xidel - -q --extract "//img/@src" < "$1"
}

ERR=0
FILE="$1"
if get_imgs "$FILE" | grep "blogspot.com"
then
    echo "Found references to blogspot.com in '$FILE'" 1>&2
    ERR=1
fi

exit "$ERR"
