#!/usr/bin/env bash

function get_imgs() {
    xidel - -s --extract "//img/@src" < "$1"
}

function get_html {
    # shellcheck disable=SC2154
    find "$rendered" -name "*.html"
}

ERR=0
while read -r FILE
do
    if get_imgs "$FILE" | grep "blogspot.com"
    then
        echo "Found references to blogspot.com in '$FILE'" 1>&2
        ERR=1
    fi
done < <(get_html)

exit "$ERR"
