#!/usr/bin/env bash

ERR=0

while read -r F
do
    ABS=$(readlink -f "$F")
    [[ -f "$ABS" ]] || continue

    grep "[^ \t\n]" < "$ABS" > /dev/null || {
        ERR=1
        echo "File '$F' looks empty" 1>&2
    }
done < <(find "$rendered" | grep -v "/git")

while read -r D
do
    ERR=1
    echo "Directory '$D' is empty" 1>&2
done < <(find "$rendered" -type d -empty | grep -v "/git")

exit "$ERR"
