#!/usr/bin/env bash

ERR=0

function noGit {
    # shellcheck disable=SC2154
    find "$rendered" | grep -v "/git"
}

while read -r F
do
    ABS=$(readlink -f "$F")
    [[ -f "$ABS" ]] || continue

    grep "[^ \t\n]" < "$ABS" > /dev/null || {
        ERR=1
        echo "File '$F' looks empty" 1>&2
    }
done < <(noGit)

function emptyDirs {
    # shellcheck disable=SC2154
    find "$rendered" -type d -empty | grep -v "/git"
}

while read -r D
do
    ERR=1
    echo "Directory '$D' is empty" 1>&2
done < <(emptyDirs)

exit "$ERR"
