#!/usr/bin/env bash
set -e

BROKEN=""
F="$1"
GOT=$(xidel - -q -e '//script[@src]/@src' < "$F")
[[ -n "$GOT" ]] || exit 0

if grep '<script *[^>]*/>' < "$F"
then
    BROKEN="$BROKEN $F"
fi

[[ -z "$BROKEN" ]] && exit 0

echo "Self-closing script tags found. This is invalid HTML, and messes up"  1>&2
echo "any content which follows. This is probably caused by putting"        1>&2
echo "'<script src=\"...\"></script>' all on one line, which Pandoc shrinks"1>&2
echo "shrinks down to '<script src=\"...\"/>'. If so, put a newline between"1>&2
echo "the open and close tags; that should be enough for Pandoc to leave"   1>&2
echo "it."                                                                  1>&2

fail "These pages contain self-closing script tags (invalid HTML): $BROKEN"
