#!/usr/bin/env bash
set -e

function pages {
    # shellcheck disable=SC2154
    find -L "$rendered" -iname '*.html'
}

BROKEN=""
while read -r F
do
    GOT=$(xidel - -q -e '//script[@src]/@src' < "$F")
    [[ -n "$GOT" ]] || continue

    if grep '<script *[^>]*/>' < "$F"
    then
        BROKEN="$BROKEN $F"
    fi
done < <(pages)

[[ -z "$BROKEN" ]] && exit 0

echo "Self-closing script tags found. This is invalid HTML, and messes up"  1>&2
echo "any content which follows. This is probably caused by putting"        1>&2
echo "'<script src=\"...\"></script>' all on one line, which Pandoc shrinks"1>&2
echo "shrinks down to '<script src=\"...\"/>'. If so, put a newline between"1>&2
echo "the open and close tags; that should be enough for Pandoc to leave"   1>&2
echo "it."                                                                  1>&2

fail "These pages contain self-closing script tags (invalid HTML): $BROKEN"
