#!/usr/bin/env bash

# Ensure old URLs, which are scattered around the Web, will resolve to something
MISSING=""
for URL in data_custom/prelude.txt
do
    [[ -e "$rendered/$URL" ]] || MISSING="$MISSING $URL"
done

[[ -z "$MISSING" ]] || {
    echo "Missing content for: $MISSING" 1>&2
    exit 1
}
