#!/usr/bin/env bash

# Ensure old URLs, which are scattered around the Web, will resolve to something
MISSING=""
URL='data_custom/prelude.txt'

# shellcheck disable=SC2154
[[ -e "$rendered/$URL" ]] || MISSING="$MISSING $URL"

[[ -z "$MISSING" ]] || {
    echo "Missing content for: $MISSING" 1>&2
    exit 1
}
