#!/usr/bin/env bash
xidel - -q --extract "//div[@id='content']//ul/li/a" < rendered/blog.html |
    while read -r TITLE
    do
        if [[ -z "$TITLE" ]]
        then
            echo "Missing title!" >> /dev/stderr
            exit 1
        fi
    done
