#!/usr/bin/env bash

function mkPage {
    echo -e '---\ntitle: Test\n---\n\n# Foo #\n\n<details>'
    echo -e '<summary>Sum</summary>\n\nBar\n\n</details>\n\nBaz'
}

GOT=$(mkPage | pandoc -t html)
echo "$GOT" | grep '<p><summary' > /dev/null || {
    echo "Pandoc doesn't wrap summaries any more" 1>&2
    echo "$GOT" 1>&2
    exit 1
}

CLEAN=$(echo "$GOT" | cleanup)
if echo "$CLEAN" | grep '<p><summary' > /dev/null
then
    echo "cleanup failed to unwrap summaries" 1>&2
    echo "$GOT" 1>&2
    echo "$CLEAN" 1>&2
    exit 1
fi

echo "$CLEAN" | grep '<summary' > /dev/null || {
    echo "cleanup removed summary" 1>&2
    echo "$GOT"   1>&2
    echo "$CLEAN" 1>&2
    exit 1
}

exit 0
