#!/usr/bin/env bash

function fail {
    echo "FAIL: $1" 1>&2
    exit 1
}

function allowedPatterns {
    # Data URIs can contain whitespace (indeed, they *should* according to the
    # base64 spec!)
    echo "Warning: <img> discarding newline in URI reference"
}

function check {
    # Return immediately if tidy is OK
    if STDERR=$(tidyCheck < "$1")
    then
        return
    fi

    # Ignore things we don't care too much about (e.g. READMEs)
    if lax "$1"
    then
        echo "Ignored tidy errors for '$1'" 1>&2
        return
    fi

    # Otherwise, abort
    echo -e "Tidy failed for '$1':\n\n$STDERR\n\n---\nEnd report for '$1'\n\n" 1>&2
    return 1
}

function tidyCheck {
    # Return immediately if tidy gives no errors
    TIDYERR=$(tidy -e 2>&1) && return

    # There doesn't seem to be a way to disable individual checks,
    # so we skip them ourselves

    WARNINGS=$(echo "$TIDYERR"          |
               grep "^Tidy found"       |
               grep -o "[0-9]* warning" |
               grep -o "[0-9]*")

    ERRORS=$(echo "$TIDYERR"        |
             grep "^Tidy found"     |
             grep -o "[0-9]* error" |
             grep -o "[0-9]*")

    TOTAL=$(( WARNINGS + ERRORS ))

    ALLOWED=0
    OUTPUT="$TIDYERR"


    while read -r PAT
    do
        OUTPUT=$(echo "$OUTPUT" | grep -v "$PAT")

        FOUND=$(echo "$TIDYERR" | grep -c "$PAT")
        ALLOWED=$(( ALLOWED + FOUND ))
    done < <(allowedPatterns)

    if [[ "$TOTAL" -gt "$ALLOWED" ]]
    then
        echo "$OUTPUT"
        return 1
    fi
}

function lax {
    # Allow warnings/errors for unfinished posts
    echo "$1" | grep "rendered/unfinished/" >/dev/null && return

    # Allow warnings/errors for git READMEs (since they might not be ours)
    echo "$1" | grep "/repos/" > /dev/null && return

    return 1
}

ERR=0
while read -r FILE
do
    check "$FILE" || ERR=1
done < <(find rendered -name "*.html")

exit "$ERR"
