#!/usr/bin/env bash

ERR=0

# root/static/null for PanPipe should be associated with .unwrap for PanHandle
while read -r LINE
do
    echo "static/null should be unwrapped: $LINE" >> /dev/stderr
    ERR=1
done < <(grep -r "root/static/null" . | grep -v "\.unwrap" | grep -v "./tests/")

exit "$ERR"
