# We host a bunch of git repos; look up their location from the environment
{ }:
with rec {
  inherit (builtins) getEnv trace;
  env = getEnv "GIT_REPO_DIR"; # User-provided override
  remote = "http://chriswarbo.net/git"; # "Official" remote; default
}; {
  base = if env != "" then
    env
  else
    trace ''
      INFO: Getting repos from ${remote}. You can override this by setting the
            GIT_REPO_DIR environment variable.
    '' remote;

  # We used to read these from a local folder, or from the directory listing of
  # chriswarbo.net/git. However, that introduced too much coupling, which we
  # prefer to avoid.
  # TODO: Add tests that compare this list to chriswarbo.net/git,
  # github.com/Warbo, and any other places we're mirroring.
  repos = [
    "annotatedb"
    "ant-colony"
    "apt-repo-tools"
    "arbitrary-haskell"
    "arduino-json-client"
    "arrowlets-for-nodejs"
    "ast-plugin"
    "asv-nix"
    "benchmark-runner"
    "bitbitjump-maude"
    "bucketing-algorithms"
    "bugseverywhere"
    "cabal2db"
    "chriswarbo-net"
    "chrome-duplicate-tab-detector"
    "clutter-file-browser"
    "dependent-types-talk"
    "desktop-scripts"
    "explore-theories"
    "feed2maildir"
    "general-tests"
    "genetic-turing-machines"
    "genifunctors"
    "get-deps"
    "ghc-base-asts"
    "ghc-dup"
    "git2html"
    "gnucleon-clutter"
    "gnucleon"
    "gpu-simulations"
    "gravity-spiral"
    "haskell-te"
    "hipspec"
    "hs2ast"
    "hs2ast-tests"
    "html-inliner"
    "iddish"
    "ifcxt"
    "iron"
    "isahipster"
    "isaplanner"
    "isaplanner-tip"
    "java-gnucleon"
    "java-maxint"
    "java-package-installer"
    "javascript-base64"
    "java-spider"
    "json-to-msgpack"
    "js-plumb"
    "k-means"
    "laminar-config"
    "lazy-lambda-calculus"
    "lazy-smallcheck-2012"
    "mc-aixi-ctw"
    "md2pdf"
    "ml4hsfe"
    "ml4hs-helper"
    "ml4hs"
    "ml4pg"
    "mlspec-bench"
    "mlspec-helper"
    "mlspec"
    "music-scripts"
    "nix-config"
    "nix-eval"
    "nix-helpers"
    "nix-lint"
    "ocportal-salmon"
    "order-deps"
    "panhandle"
    "panpipe"
    "particle-storage-ring-simulation"
    "php-core"
    "php-easycheck"
    "php-plumb"
    "php-prelude"
    "powerplay"
    "pubsubclient"
    "purely-functional-self-modifying-code"
    "python-app-prefs"
    "python-clutter-experiments"
    "python-decompiler"
    "python-examples"
    "python-graphics-tests"
    "python-pipes-simulation"
    "python-plumb"
    "python-random-walks"
    "python-visualiser"
    "quickcheck"
    "quickspeccer"
    "quickspec"
    "quickspec-measure"
    "recurrent-clustering"
    "reduce-equations"
    "render-eqs"
    "runtime-arbitrary"
    "runtime-arbitrary-tests"
    "run-weka"
    "sample-bench"
    "search-optimisation-streams"
    "service-packs"
    "spoon"
    "stp-sites"
    "theory-exploration-benchmarks"
    "tinc"
    "tip-benchmarks"
    "tip-tools"
    "tree-features"
    "turtleviewer"
    "type-parser"
    "warbo-dotfiles"
    "warbo-emacs-d"
    "warbo-packages"
    "warbo-utilities"
    "writing"
    "wtk"
  ];
}
