#!/bin/sh
CODE=$(cat)

DIR=$(dirname "$0")
echo "$CODE" | "$DIR/$2Code" > "$1.hs"
runhaskell -i"$DIR" "$1.hs" > "$1.ppm"
{ echo "$CODE" | wrapCode .haskell
  echo ""
  "$DIR/includePic" "$1" | wrapCode .unwrap
} >> "$1.md"
pandoc -t json < "$1.md"
