#!/usr/bin/env bash
[[ -n "$1" ]] || exit 0
[[ -f "$1" ]] || {
    echo "Can't get dependencies of '$1'" >> /dev/stderr
    exit 1
}

grep "dependencies[ ]*:" < "$1" | sed -e 's/.*dependencies[ ]*://g'
