#!/usr/bin/env python
from bs4 import BeautifulSoup
import fileinput

stdin = reduce(lambda content, line: content + line, fileinput.input(), "")
doc   = BeautifulSoup(stdin, 'html.parser')

def unwrap(e):
    """Matches '<pre class="htmlunwrap"><code>foo</code></pre>' and splices the literal
    content 'foo' into the HTML."""
    try:
        if 'htmlunwrap' not in e['class']:
            return
    except KeyError:
        pass
    code    = e.code
    content = BeautifulSoup(''.join(code.strings), 'html.parser')
    e.replace_with(content)

map(unwrap, doc.find_all('pre'))

print(doc)
