#!/usr/bin/env python3
from bs4 import BeautifulSoup
import fileinput
from functools import reduce

stdin = reduce(lambda content, line: content + line, fileinput.input(), "")
doc   = BeautifulSoup(stdin, 'html.parser')

def unwrap(e):
    """Matches '<pre class="htmlunwrap"><code>foo</code></pre>' and splices the literal
    content 'foo' into the HTML."""
    try:
        if 'htmlunwrap' not in e['class']:
            return
    except KeyError:
        return
    code    = e.code
    content = BeautifulSoup(''.join(code.strings), 'html.parser')
    e.replace_with(content)

for pre in doc.find_all('pre'):
    unwrap(pre)

print(doc)
