#!/usr/bin/env bash

# Update a HTML file to use relative links, e.g. '../css/foo.css' rather than
# '//chriswarbo.net/css/foo.css' or '/css/foo.css'

# This file should not be run standalone; it should be wrapped in an appropriate
# environment by default.nix

set -e

FILE="$1"

if [[ -z "$TO_ROOT" ]]
then
    # Determine the path to the Web root, e.g. '../..'
    P=$(dirname "$FILE" | sed -e 's@.*rendered/@@g' |
                          sed -e 's@.*rendered@@g'  |
                          sed -e 's@[^/][^/]*@..@g')
    if [[ -n "$P" ]]
    then
        TO_ROOT="$P"
    else
        TO_ROOT="."
    fi
fi

# Modify HTML

# Prefix anchor hyperlinks
xmlstarlet ed -u "//a[starts-with(@href, '/')]/@href" \
              -x "concat('$TO_ROOT', .)" < "$FILE" > "$FILE.rel"
mv -v "$FILE.rel" "$FILE"

# Prefix links
xmlstarlet ed -u "//link[starts-with(@href, '/')]/@href" \
              -x "concat('$TO_ROOT', .)" < "$FILE" > "$FILE.rel"
mv -v "$FILE.rel" "$FILE"
