#!/usr/bin/env bash

# Update a HTML file to use relative links, e.g. '../css/foo.css' rather than
# '//chriswarbo.net/css/foo.css' or '/css/foo.css'

set -e

if [[ -z "$TO_ROOT" ]]
then
    echo "No TO_ROOT given, aborting" 1>&2
    exit 1
fi

INPUT=$(cat)

# If the document specifies a default namespace, we must prefix all of our
# queries with it
NAMESPACE=""
if echo "$INPUT" | grep -o 'xmlns="[^"]*"' > /dev/null
then
    NAMESPACE=$(echo "$INPUT" | grep -o 'xmlns="[^"]*"' |
                                head -n1                |
                                grep -o '".*'           |
                                grep -o '[^"]*')

    # These arguments should be spliced into any xmlstarlet commandline we run
    NAMESPACEARGS=( -N "ns=$NAMESPACE" )

    # This prefix should be spliced before any identifier in our queries
    NS="ns:"
fi

function prefix() {
    # $1 is an element name (which we prefix with a namespace if needed)
    # $2 is an attribute name
    # We prefix any matching attributes of matching elements given on stdin,
    # with the value of $TO_BASE
    xmlstarlet ed ${NAMESPACEARGS[@]} \
               -u "//${NS}${1}[starts-with(@${2}, '/')]/@${2}" \
               -x "concat('$TO_ROOT', .)"
}

echo "$INPUT" | prefix a      href |
                prefix link   href |
                prefix script src  |
                prefix img    src
