#!/usr/bin/env python

from bs4 import BeautifulSoup
import fileinput
import sys

stdin = reduce(lambda content, line: content + line, fileinput.input(), "")
doc   = BeautifulSoup(stdin, 'html.parser')

def remove_if_empty(tag):
    def f(e):
        if repr(e) == '<' + tag + '></' + tag + '>':
            sys.stderr.write('Removing empty element "' + repr(e) + '"\n')
            e.extract()
    return f

remove_empty = lambda tag: map(remove_if_empty(tag), doc.find_all(tag))

# Empty <code> elements are left over from running commands with PanPipe. Tidy
# complains about them, so we might as well remove them.
# Remove <code> elements first, then remove any containers (<span>, <p> and
# <pre> elements) which might have contained those <code> elements and are
# subsequently empty.
map(remove_empty, ['code', 'pre', 'span', 'p'])

print(doc)
