#!/usr/bin/env python

from bs4 import BeautifulSoup
import fileinput

stdin = reduce(lambda content, line: content + line, fileinput.input(), "")
doc   = BeautifulSoup(stdin, 'html.parser')

for summarise in doc.find_all(class_='summarise'):
    for summary in summarise.find_all(class_='summary'):
        summarise.table['summary'] = reduce(
            lambda ttl, txt: ttl + txt,
            summary.strings,
            "").strip()
        highest = summary
        drop = True
        for parent in summary.parents:
            if drop:
                if parent == summarise:
                    drop = False
                else:
                    highest = parent
        highest.extract()

print(doc)
