#!/usr/bin/env python

from bs4 import BeautifulSoup
import fileinput
import sys

stdin = reduce(lambda content, line: content + line, fileinput.input(), "")
doc   = BeautifulSoup(stdin, 'html.parser')

def unwrap(e):
    """Matches '<p><summary>foo</summary></p>' and replaces it with
    '<summary>foo</summary>'"""
    p = e.parent

    # Only unwrap paragraphs if this summary is the only thing in it
    if p.name == u'p' and [c.name for c in p.contents] == [u'summary']:
        p.replace_with(e)

map(unwrap, doc.find_all('summary'))

print(doc)
